-- codificación UTF-8: Reconocer Tildes, Emojis..etc
SET NAMES 'utf8mb4';

DROP DATABASE IF EXISTS HOGWARTSWEB;
CREATE DATABASE HOGWARTSWEB ;
USE HOGWARTSWEB;

-- Creacion de la Tabla Usuarios
CREATE TABLE USUARIO(
    ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Usuario',
    NOMBRE VARCHAR(45) NOT NULL COMMENT 'Nombre del Usuario',
    CORREO VARCHAR(45) NOT NULL COMMENT 'Correo Electronico del Usuario',
    CONTRASEÑA INT NOT NULL COMMENT 'Contraseña del Usuario',
    CASA VARCHAR(45) NULL COMMENT 'Casa del Usuario',
    PUNTOS INT NULL COMMENT 'Puntos del Usuario',
    CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO)
    
);
CREATE TABLE OBJETO(
    ID_OBJETO INT PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Objeto',
    NOMBRE VARCHAR(45) NOT NULL COMMENT 'Nombre del Objeto',
    DESCRIPCION VARCHAR(75) NOT NULL COMMENT 'Descripcion del Objeto',
    COSTE INT NOT NULL COMMENT 'Coste del Objeto',
    CONSTRAINT PK_ID_OBJETO PRIMARY KEY (ID_OBJETO)
);

CREATE TABLE PERSONAJE(
    ID_PERSONAJE INT PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Personaje',
    NOMBRE VARCHAR(45) NOT NULL COMMENT 'Nombre del Personaje',
    DESCRIPCION VARCHAR(75) NOT NULL COMMENT 'Descripcion del Personaje',
    CASA VARCHAR(45) NULL COMMENT 'Casa del Personaje',
    CONSTRAINT PK_ID_PERSONAJE PRIMARY KEY (ID_PERSONAJE)
);

CREATE TABLE COMENTARIO(
    ID_COMENTARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Comentario',
    DESCRIPCION VARCHAR(75) NOT NULL COMMENT 'Descripcion del Comentario',
    VALORACION TINYINT NOT NULL COMMENT 'Valoracion del Comentario',
    -- TINYINT: Es como el INT, pero reducido. Ocupa un solo Byte
    CONSTRAINT PK_ID_COMENTARIO PRIMARY KEY (ID_COMENTARIO)
);

-- Lo llamo COMPRA porque poner Usuario_Objeto no me gusta
-- Relacion N:M Usuario <-> Objeto
CREATE TABLE COMPRA(
    ID_COMPRA INT PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la Compra',
    ID_USUARIO INT NOT NULL COMMENT 'Identificador del Usuario',
    ID_OBJETO  INT NOT NULL COMMENT 'Identificador del Objeto',
    CONSTRAINT PK_ID_COMPRA PRIMARY KEY (ID_COMPRA)
    CONSTRAINT FK_COMPRA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
    CONSTRAINT FK_COMPRA_OBJETO FOREIGN KEY (ID_OBJETO) REFERENCES OBJETO(ID_USUARIO)
);
