events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # 1. ARCHIVOS ESTÁTICOS DE REACT
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            # Crucial para que React Router no rompa al actualizar pantallas como /login o /registrarse
            try_files $uri $uri/ /index.html; 
        }

        # 2. EL PUENTE HACIA EL BACKEND (¡Ojo a la barra final!)
        location /api/ {
            # Redirige de forma limpia a tu Back de Railway
            proxy_pass http://back-production-834d.up.railway.app/; 
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Evita problemas de timeouts en peticiones largas
            proxy_connect_timeout 90;
            proxy_send_timeout 90;
            proxy_read_timeout 90;
        }
    }
}