spring.application.name=HarryPotter

# IMPORTANTE: Permite que Railway asigne su puerto dinámico, o usa 9090 en tu PC
server.port=${PORT:9090}

# URL HÍBRIDA: Usa Railway en la nube o 'localhost' en tu PC (reemplazando 'db')
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hogwartsweb?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect